### ISSUE TITLE
outside link imodeljs,zoomToElements

### ISSUE THREAD

**Issue by paprophet** [imodeljs/imodeljs#140]
now ,outside webpage link modeljs project,
i want use  [await vp.zoomToElements(state.elementList, { ...viewChangeOpts, ...zoomToOpts });]
but the vp is undefined,so i want write callback function after then imodeljs load complete ,but i donot know when the imodeljs load complete ?
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Community-Resources---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/learning/communityresources/

**Comment by pmconne** [comment]
iModel.js itself doesn't automatically open any viewports; applications do so. Are you trying to do this in the context of a specific app? If so, which one?
If you just want to intercept the first viewport that gets opened, you can do something like:
```ts
IModelApp.viewManager.onViewOpen.addOnce((vp) => {
  vp.zoomToElements(state.elementList, { ...viewChangeOpts, ...zoomToOpts });
});
```
However, it sounds like you expect a specific iModel to be opened in the viewport - otherwise how would you know which elements to zoom to? - so there's probably a better place in your app where you could add your code.

**Comment by pmconne** [comment]
Closing as "question, not issue". Feel free to follow up in [Discussion](https://github.com/imodeljs/imodeljs/discussions) if necessary.
