### ISSUE TITLE
After the execution of “npm install" is completed,but not generate  the script of "start"

### ISSUE THREAD

**Issue by maoyankandanteng** [imodeljs/imodeljs#38]
![1](https://user-images.githubusercontent.com/23349116/62362968-bdedcc00-b550-11e9-83b6-ff945dd2ec2f.png)

**Comment by pmconne** [comment]
Please consult the simple-viewer-app README: https://github.com/imodeljs/simple-viewer-app
There are several options for starting the app depending on whether you want to run it in electron or a browser, and whether you want to start the webserver, the backend, or both.
To start it so that you can run it in a browser on localhost, use: `npm run start:servers`
