### ISSUE TITLE
I couldn't open the local ibim file using simple-viewer-app.

### ISSUE THREAD

**Issue by shenshengyi** [imodeljs/imodeljs#52]
I couldn't open the local ibim file using simple-viewer-app.
Always prompt Invalid iModelToken for RPC operation request，Can you help me? thanks.
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Getting-Started-With-iModel.js---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://imodeljs.github.io/iModelJs-docs-output/getting-started/

**Comment by wilmaier** [comment]
I discovered that due to recent changes, the feature of opening a snapshot imodel using the “Work Offline” button is no longer working.
A new version with a fix should be available in the next couple days.

One thing I should mention is that this feature is not supported for web apps.  
The ‘Work Offline’ button will only be available when the app is run as an electron app (npm run electron).

**Comment by wilmaier** [comment]
This issue is now resolved in the latest version.

**Comment by shenshengyi** [comment]
Thank you very much, I have solved this problem.
