### ISSUE TITLE
can i open .dgn file by imodel.js

### ISSUE THREAD

**Issue by asforever** [imodeljs/imodeljs#6]
like title

**Comment by LabyrinthTechnology** [comment]
Hi,

no, it's not possible. iModelJs is based on [EC schema](https://imodeljs.github.io/iModelJs-docs-output/bis/ec/ec-schema/) and [BIS definitions](https://imodeljs.github.io/iModelJs-docs-output//bis/), whereas DGN is proprietary implementation of Microsoft Compound File format.

It's possible to convert DGN into "BIS based description" using [iModel Bridge(s)](https://imodeljs.github.io/iModelJs-docs-output/learning/imodel-bridges/).

With regards,

&nbsp;&nbsp;Jan

**Comment by asforever** [comment]
thanks😊

**Comment by wuyw1015** [comment]
Hi,
can i read .imodel data by modeljs? ,are there some limitations in .imodel's version and ...?，i try to run" imodeljs/test-apps/simpleviewtest/", but the feedback below:
![image](https://user-images.githubusercontent.com/24538966/47974634-7e8b6f80-e0e5-11e8-8d90-b33f69c831e9.png)

and i can open .model by navicat premium
![image](https://user-images.githubusercontent.com/24538966/47974841-6536f300-e0e6-11e8-826a-db4380d3d5c4.png)

**Comment by LabyrinthTechnology** [comment]
Hi @wuyw1015,

because the original question was about .dgn support, in my opinion it would be better to ask in a new post, because .dgn is not .imodel, so it's another question / issue.

In my opinion iModel 2 is supported only and older versions (1.5, 1.6) created by MicroStation and other products (as output from DgnDb convertor) are not supported. Based on #5 my assumption is that older imodel formats have to be converted / mapped using iModel Bridge.

@ColinKerr, would you be so kind and to confirm / disprove this? ;-)

With regards,

&nbsp;&nbsp;Jan

**Comment by wuyw1015** [comment]
@LabyrinthTechnology  thx, are there any suggestions about the new issue [new issue ](https://github.com/imodeljs/imodeljs/issues/6)?

**Comment by ColinKerr** [comment]
iModel.js only supports the iModel 2.0 file format, not versions 1.5 and 1.6.  

Both questions are important and we are working on more complete responses, please bear with us.

**Comment by roopsaini** [comment]
The original question has been answered. This discussion now pertains to data conversion, which falls under #12 (marked as an enhancement).
