### ISSUE TITLE
unauthorized client : Invalid Grant Type

### ISSUE THREAD

**Issue by aderderian** [imodeljs/imodeljs#70]
Redirect uris look good in iModelHub and in local front-end application. I am getting the following error :

![image](https://user-images.githubusercontent.com/868165/74999918-e07efe00-542a-11ea-8f8e-20feb21c3901.png)

I added all grants to the application I am testing with and this did not seem to fix the issue. I am testing using https://localhost:44883 in my own application.

For more information please refer to SEQ logs using this query:
@Timestamp < DateTime('2020-02-21T02:59:23.999797Z') and RequestId='0HLTLGMUOA1FM:0000092A'

![image](https://user-images.githubusercontent.com/868165/75000468-65b6e280-542c-11ea-8757-b4754ee6879c.png)

**Comment by williamkbentley** [comment]
This happens because the grant_type of your client does not match with what is set in `OidcFrontendClientConfiguration`. You can check the grant_type of your client by going to the [registration dashboard](https://www.imodeljs.org/getting-started/registration-dashboard). `grant_type` is not displayed in the list of registered apps, but you can find the request in the network tab, look for spa-< guid > and find `grantType` in the response. I am guessing you created your app previously and it is `implicit`. You will either need to change the `OidcFrontendClientConfiguration` to `implicit`, but it is recommended to create a new SPA. The new SPA will have grant_type `authorization_code` will work with the code as currently published. `auth_code` is more secure than `implicit`

**Comment by aderderian** [comment]
Hey @williamkbentley  I don't see a network tab in my Registration Dashboard. I am using the latest code from simple-viewer-app, but I went into the "Allowed Scopes" area for the app and added all scopes as well as in the imjs_browser_test_scope variable in the app to match. Any clue on where this Network tab might be or why it is missing?

**Comment by williamkbentley** [comment]
Oh, sorry. I meant network tab *on developer console* (F12). 
Ex: 
![image](https://user-images.githubusercontent.com/38542573/75053347-1d84d800-549f-11ea-916c-5acefd64e4c1.png)

**Comment by aderderian** [comment]
Ah. Well creating a new app seems to have solved this issue. Thanks for that advice! Is there a spot in the docs you could point me to that describes what all the scopes cover? 

Thanks again for your help!

**Comment by williamkbentley** [comment]
Apart from the standard [oidc scopes](https://auth0.com/docs/scopes/current/oidc-scopes). Most others are just used to access various Bentley services. [We have this page](https://www.imodeljs.org/getting-started/application-scopes/?term=available+scopes), but it could certainly use some improvement.

**Comment by aderderian** [comment]
Cool thx. This one can be closed. I have two others I need your help on too!
